import AppKit

/// Polls NSPasteboard's change count (macOS has no clipboard-change notification)
/// and reports each new, non-concealed item.
public final class PasteboardWatcher {
    public static let concealedTypes: Set<String> = [
        "org.nspasteboard.ConcealedType",   // password managers
        "org.nspasteboard.TransientType",
        "org.nspasteboard.AutoGeneratedType",
    ]

    private let pasteboard: NSPasteboard
    private let onCapture: (ClipPayload) -> Void
    private var lastChangeCount: Int
    private var timer: Timer?

    public init(pasteboard: NSPasteboard = .general, onCapture: @escaping (ClipPayload) -> Void) {
        self.pasteboard = pasteboard
        self.onCapture = onCapture
        self.lastChangeCount = pasteboard.changeCount
    }

    public func start(interval: TimeInterval = 0.4) {
        stop()
        timer = Timer.scheduledTimer(withTimeInterval: interval, repeats: true) { [weak self] _ in self?.poll() }
    }

    public func stop() {
        timer?.invalidate()
        timer = nil
    }

    /// Call after Clipbook itself writes to the pasteboard so it isn't re-captured.
    public func ignoreCurrentContents() {
        lastChangeCount = pasteboard.changeCount
    }

    public func poll() {
        guard pasteboard.changeCount != lastChangeCount else { return }
        lastChangeCount = pasteboard.changeCount
        if let payload = Self.payload(from: pasteboard) { onCapture(payload) }
    }

    /// Files > image > text, skipping concealed items.
    public static func payload(from pasteboard: NSPasteboard) -> ClipPayload? {
        let types = Set((pasteboard.types ?? []).map(\.rawValue))
        if !types.isDisjoint(with: concealedTypes) { return nil }

        if let urls = pasteboard.readObjects(forClasses: [NSURL.self], options: [.urlReadingFileURLsOnly: true]) as? [URL],
           !urls.isEmpty {
            return .files(urls.map(\.path))
        }
        if let png = pasteboard.data(forType: .png) {
            return .image(png)
        }
        if let tiff = pasteboard.data(forType: .tiff),
           let rep = NSBitmapImageRep(data: tiff),
           let png = rep.representation(using: .png, properties: [:]) {
            return .image(png)
        }
        if let s = pasteboard.string(forType: .string), !s.isEmpty {
            return .text(s)
        }
        return nil
    }
}
